// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB.Global.proto

#include "PB.Global.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace PB {
}  // namespace PB
namespace protobuf_PB_2eGlobal_2eproto {
void InitDefaults() {
}

}  // namespace protobuf_PB_2eGlobal_2eproto
namespace PB {
bool ERR_IsValid(int value) {
  switch (value) {
    case 0:
    case 1028:
    case 1280:
    case 20481:
    case 20482:
    case 20483:
    case 20485:
    case 5242880:
    case 5243136:
    case 5243137:
    case 5243392:
    case 5243393:
    case 5243394:
    case 5244674:
    case 5246977:
    case 5246978:
      return true;
    default:
      return false;
  }
}

bool COMMAND_IsValid(int value) {
  switch (value) {
    case 20481:
    case 20482:
    case 20483:
    case 20484:
    case 24576:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace PB
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
