// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB.Global.proto

#ifndef PROTOBUF_INCLUDED_PB_2eGlobal_2eproto
#define PROTOBUF_INCLUDED_PB_2eGlobal_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_PB_2eGlobal_2eproto 

namespace protobuf_PB_2eGlobal_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_PB_2eGlobal_2eproto
namespace PB {
}  // namespace PB
namespace PB {

enum ERR {
  ERR_NO = 0,
  ERR_SYSTEM = 1280,
  ERR_REASON_NO_ROUTE_SERVER = 20481,
  ERR_REASON_NO_LOGIN_SERVER = 20482,
  ERR_REASON_NO_DB_SERVER = 20483,
  ERR_SERVER_NOT_FOUND = 1028,
  ERR_PB_PARSE_ERROR = 20485,
  ERR_AUTH_LOGIN_ERROR = 5242880,
  ERR_USERNAME_EXISTS = 5243136,
  ERR_USERNAME_INVALID = 5243137,
  ERR_GROUP_CREATE_PAIR_GROUP_MEMBER_SIE_INVALID = 5243392,
  ERR_GROUP_CREATE_PAIR_GROUP_NO_REG_USER = 5243393,
  ERR_GROUP_HAS_CREATED = 5243394,
  ERR_SWITCH_USER_NO_ONLINE = 5244674,
  ERR_CLIENT = 5246977,
  ERR_CLIENT_TIMEOUT = 5246978
};
bool ERR_IsValid(int value);
const ERR ERR_MIN = ERR_NO;
const ERR ERR_MAX = ERR_CLIENT_TIMEOUT;
const int ERR_ARRAYSIZE = ERR_MAX + 1;

enum COMMAND {
  COMMAND_FILE_UPLOAD_REQUEST = 20481,
  COMMAND_FILE_UPLOAD_RESPONSE = 20482,
  COMMAND_FILE_DOWNLOAD_REQUEST = 20483,
  COMMAND_FILE_DOWNLOAD_RESPONSE = 20484,
  COMMAND_HEART_BEAT_NOTIFY = 24576
};
bool COMMAND_IsValid(int value);
const COMMAND COMMAND_MIN = COMMAND_FILE_UPLOAD_REQUEST;
const COMMAND COMMAND_MAX = COMMAND_HEART_BEAT_NOTIFY;
const int COMMAND_ARRAYSIZE = COMMAND_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace PB

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PB::ERR> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::COMMAND> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_PB_2eGlobal_2eproto
