# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.162.0/containers/cpp/.devcontainer/base.Dockerfile

# [Choice] Debian / Ubuntu version: debian-10, debian-9, ubuntu-20.04, ubuntu-18.04
ARG VARIANT="ubuntu-20.04"
FROM sanfun/ptp-cpp:0-${VARIANT}

#RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#    && apt-get -y install --no-install-recommends curl \
#    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*
